import { FormEvent, TouchEvent, useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowRight, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ClipboardCheck, Clock3, Leaf, LockKeyhole, PackageCheck, ShieldCheck, ShoppingBag, TimerReset } from "lucide-react";
import { trpc } from "@/lib/trpc";

const A = {
  hero: "/manus-storage/tempo-brand-hero_6c096b85.png", logo: "/manus-storage/v2joylogo-official_9302769f.webp", product: "/manus-storage/tempo-pack-front_9e2c58ea.png", sides: "/manus-storage/tempo-pack-sides_99932a67.png", back: "/manus-storage/tempo-pack-back_267c13e5.png", hands: "/manus-storage/tempo-couple-hands_6b173623.png", benefits: "/manus-storage/tempo-benefits_e53327fd.png", steps: "/manus-storage/tempo-use-steps_a7b53030.png", wait: "/manus-storage/tempo-wait-ritual_0db05ba8.png", carry: "/manus-storage/tempo-carry_5d2617d2.png", unbox: "/manus-storage/tempo-unbox_7fe4ee69.png", detail: "/manus-storage/tempo-design-detail_b6e6ad35.png", story: "/manus-storage/tempo-story_fc38bf3c.png", label: "/manus-storage/tempo-claim-label_10f35a7d.png",
  exit: "/manus-storage/tempo-lifestyle-01-exit-evening_334132f2.webp", walk: "/manus-storage/tempo-couple-04-walk-home-woman-man_8da9bbe8.png", ritual: "/manus-storage/tempo-ritual-01-quiet-preparation_c68f7133.webp", kitchen: "/manus-storage/tempo-couple-03-kitchen-evening-woman-man_9c71be8e.png", morning: "/manus-storage/tempo-lifestyle-04-morning-return_a7805e20.webp",
  v1: "/manus-storage/1-3_488cdaeb.mp4", v2: "/manus-storage/2-2_1c24d56b.mp4", v3: "/manus-storage/3-2_1be35ced.mp4", v4: "/manus-storage/4-2_5b3104ee.mp4", v5: "/manus-storage/5-2_104c988a.mp4",
} as const;

const INCI = "Purified Water, Alcohol (Ethanol), Butylene Glycol, Cnidium monnieri extract (Chiết xuất Xà Sàng Tử), Zanthoxylum bungeanum extract (Chiết xuất Hoa Tiêu), Sophora flavescens extract (Chiết xuất Khổ Sâm), Polygonatum sibiricum extract (Chiết xuất Hoàng Tinh), Eucommia ulmoides extract (Chiết xuất Đỗ Trọng), Cynomorium songaricum extract (Chiết xuất Tỏa Dương), Epimedium brevicornum extract (Chiết xuất Dâm Dương Hoắc), Verbena officinalis extract (Chiết xuất Mã Tiên Thảo), Morinda officinalis extract (Chiết xuất Ba Kích Thiên), Sodium Benzoate, Panthenol.";
const diary = [
  { image: A.exit, index: "01", kicker: "RỜI NGÀY DÀI", title: "Khép lại ngày dài", copy: "Rời lịch làm việc và để lại một khoảng vừa đủ cho chính mình." },
  { image: A.walk, index: "02", kicker: "TRÊN ĐƯỜNG VỀ", title: "Để lại khoảng vội", copy: "Một nhịp chậm trước khi gặp nhau giúp buổi tối bớt phải chạy theo." },
  { image: A.ritual, index: "03", kicker: "KHOẢNG DỪNG", title: "Chọn một điểm dừng", copy: "Chăm sóc bản thân là một lựa chọn chủ động, kín đáo và bình tĩnh." },
  { image: A.kitchen, index: "04", kicker: "KHOẢNH KHẮC", title: "Có mặt cho nhau", copy: "Câu chuyện của TEMPO luôn bắt đầu từ sự tôn trọng và đồng thuận." },
  { image: A.morning, index: "05", kicker: "TRỞ VỀ", title: "Giữ nhịp vừa đủ", copy: "Một nghi thức nhẹ nhàng để trở về với nhịp riêng của hai người." },
] as const;
type Attribution = Record<"utmSource" | "utmMedium" | "utmCampaign" | "utmContent" | "utmTerm" | "fbclid", string>;
const blankAttribution: Attribution = { utmSource: "", utmMedium: "", utmCampaign: "", utmContent: "", utmTerm: "", fbclid: "" };
const scrollToOrder = () => document.getElementById("dat-hang")?.scrollIntoView({ behavior: "smooth", block: "start" });
const vnd = (value: number) => `${value.toLocaleString("vi-VN")}đ`;

function attribution(): Attribution {
  const names = { utmSource: "utm_source", utmMedium: "utm_medium", utmCampaign: "utm_campaign", utmContent: "utm_content", utmTerm: "utm_term", fbclid: "fbclid" } as const;
  try {
    const saved = JSON.parse(localStorage.getItem("tempo-attribution") || "{}") as Partial<Attribution>;
    const qs = new URLSearchParams(location.search); const data = { ...blankAttribution };
    (Object.keys(names) as (keyof Attribution)[]).forEach(key => { data[key] = qs.get(names[key])?.trim() || saved[key] || ""; });
    localStorage.setItem("tempo-attribution", JSON.stringify(data)); return data;
  } catch { return blankAttribution; }
}

function Image({ src, alt, className = "", eager = false }: { src: string; alt: string; className?: string; eager?: boolean }) {
  return <img src={src} alt={alt} className={className} loading={eager ? "eager" : "lazy"} decoding="async" onError={({ currentTarget }) => { if (!currentTarget.dataset.fallback) { currentTarget.dataset.fallback = "true"; currentTarget.src = A.hero; } }} />;
}

function Signal() { return <svg className="signal" viewBox="0 0 560 80" fill="none" aria-hidden="true"><path d="M0 43H58c30 0 29-23 56-23 29 0 25 43 56 43 33 0 25-35 56-35 35 0 23 30 58 30 29 0 27-20 57-20 27 0 30 13 56 13h56" /></svg>; }

function Backdrop({ video, poster, label, eager = false }: { video: string; poster: string; label: string; eager?: boolean }) {
  const frame = useRef<HTMLDivElement>(null); const player = useRef<HTMLVideoElement>(null);
  const [load, setLoad] = useState(eager); const [state, setState] = useState<"loading" | "playing" | "error">("loading");
  useEffect(() => {
    if (eager || load || !frame.current) return;
    const observer = new IntersectionObserver(entries => { if (entries.some(entry => entry.isIntersecting)) { setLoad(true); observer.disconnect(); } }, { rootMargin: "700px 0px" });
    observer.observe(frame.current); return () => observer.disconnect();
  }, [eager, load]);
  useEffect(() => {
    if (!load || !player.current) return; const media = player.current; let stopped = false; let retries = 0;
    const play = () => { const attempt = media.play(); attempt?.then(() => !stopped && setState("playing")).catch(() => { if (!stopped && retries++ < 3) window.setTimeout(play, 350 * retries); }); };
    const timers = [0, 300, 1100].map(delay => window.setTimeout(play, delay)); media.addEventListener("canplay", play);
    return () => { stopped = true; timers.forEach(window.clearTimeout); media.removeEventListener("canplay", play); };
  }, [load, video]);
  return <div ref={frame} className="video-frame" data-playback-state={state} aria-label={label}><Image src={poster} alt="" className="video-frame__fallback" eager={eager} />{load && <video ref={player} autoPlay muted loop playsInline preload={eager ? "auto" : "metadata"} poster={poster} onPlaying={() => setState("playing")} onError={() => setState("error")}><source src={video} type="video/mp4" /></video>}{state === "playing" && <span className="video-frame__motion-status" aria-hidden="true">VIDEO ĐANG PHÁT</span>}</div>;
}

function Scene({ step, title, accent, copy, detail, video, poster }: { step: "02" | "03" | "04" | "05"; title: string; accent: string; copy: string; detail: string; video: string; poster: string }) {
  return <section className={`video-story-scene video-story-scene--${step}`} aria-labelledby={`scene-${step}`}><Backdrop video={video} poster={poster} label={`Video ${step}: ${title}`} /><div className="video-story-scene__wash" /><div className="video-story-scene__copy"><p className="overline">CẢNH {step} / 05 · VIDEO NỀN</p><h2 id={`scene-${step}`}>{title}<br /><em>{accent}</em></h2><p>{copy}</p><div className="video-story-scene__detail"><span>ĐANG CHẠY NỀN</span><b>{detail}</b></div></div></section>;
}

function Diary() {
  const [active, setActive] = useState(0); const start = useRef<number | null>(null); const item = diary[active]; const choose = (n: number) => setActive((n + diary.length) % diary.length);
  const touchEnd = (event: TouchEvent<HTMLDivElement>) => { const end = event.changedTouches[0]?.clientX; if (start.current !== null && end !== undefined && Math.abs(end - start.current) >= 44) choose(active + (end < start.current ? 1 : -1)); start.current = null; };
  return <section className="visual-diary" aria-labelledby="diary-title"><div className="section-masthead"><p className="overline">VISUAL DIARY / TEMPO</p><h2 id="diary-title">Một buổi tối.<br /><em>Những khoảng vừa đủ.</em></h2><p>Từng khung hình là một nhịp dừng, không phải một lời hứa thay cho sự kết nối giữa hai người.</p></div><div className="visual-diary__stage" data-swipe="enabled" onTouchStart={event => { start.current = event.changedTouches[0]?.clientX ?? null; }} onTouchEnd={touchEnd}><Image src={item.image} alt={`${item.title}: ${item.copy}`} className="visual-diary__image" /><div className="visual-diary__wash" /><div className="visual-diary__copy"><span>{item.index} / 05 · {item.kicker}</span><h3>{item.title}</h3><p>{item.copy}</p></div><div className="visual-diary__controls"><button type="button" aria-label="Xem khoảnh khắc trước" onClick={() => choose(active - 1)}><ChevronLeft size={20} /></button><button type="button" aria-label="Xem khoảnh khắc tiếp theo" onClick={() => choose(active + 1)}><ChevronRight size={20} /></button></div><div className="visual-diary__tabs" role="tablist" aria-label="Các khoảnh khắc trong visual diary">{diary.map((d, index) => <button key={d.index} type="button" role="tab" aria-selected={active === index} aria-label={`${d.index}: ${d.title}`} onClick={() => choose(index)}><span>{d.index}</span></button>)}</div></div></section>;
}

const productDetails = [
  { image: A.benefits, index: "01", label: "CHĂM SÓC KÍN ĐÁO", title: "Một bước chăm sóc.\nMột khoảng riêng.", copy: "Mục đích sử dụng ghi nhận: giúp chăm sóc dưỡng ẩm da. TEMPO dành cho nhịp chuẩn bị nhẹ nhàng, không thay thế giao tiếp và sự đồng thuận." },
  { image: A.detail, index: "02", label: "THIẾT KẾ TEMPO", title: "Gọn bên ngoài.\nChu đáo từng chi tiết.", copy: "Nắp graphite, vòi xịt phun sương và dung tích 3ml được đặt trong một thiết kế tối giản, dễ cất giữ." },
  { image: A.unbox, index: "03", label: "MỞ HỘP RIÊNG TƯ", title: "Nhỏ để mang theo.\nKín đáo để chủ động.", copy: "Thiết kế kéo – đẩy gọn gàng để bạn mang theo trong túi cá nhân và bắt đầu nghi thức theo nhịp của riêng mình." },
] as const;

function ProductDetails() {
  const [active, setActive] = useState(0); const item = productDetails[active]; const choose = (next: number) => setActive((next + productDetails.length) % productDetails.length);
  return <section className="product-detail-showcase" aria-labelledby="detail-showcase-title"><div className="product-detail-showcase__intro"><p className="chapter">03 — CHI TIẾT SẢN PHẨM</p><div><h2 id="detail-showcase-title">Gọn bên ngoài.<br /><em>Chủ động bên trong.</em></h2><p>Chọn một góc nhìn để xem kỹ hơn, thay vì phải đọc mọi thông tin trong cùng một khung hình.</p></div></div><div className="product-detail-showcase__layout"><figure className="product-detail-showcase__figure"><Image src={item.image} alt={item.label} className="product-detail-showcase__image mobile-safe-square" /><figcaption><span>{item.index} / 03</span><span>{item.label}</span></figcaption></figure><div className="product-detail-showcase__panel"><p className="overline">TEMPO 3ML / {item.label}</p><h3>{item.title.split("\n").map((line, index) => <span key={line}>{index === 1 ? <em>{line}</em> : line}{index === 0 && <br />}</span>)}</h3><p>{item.copy}</p><div className="product-detail-showcase__tabs" role="tablist" aria-label="Các góc nhìn chi tiết TEMPO">{productDetails.map((detail, index) => <button key={detail.index} type="button" role="tab" aria-selected={active === index} aria-label={`${detail.index}: ${detail.label}`} onClick={() => choose(index)}><b>{detail.index}</b><span>{detail.label}</span></button>)}</div><div className="product-detail-showcase__controls"><button type="button" aria-label="Xem chi tiết trước" onClick={() => choose(active - 1)}><ChevronLeft size={19} /></button><button type="button" aria-label="Xem chi tiết tiếp theo" onClick={() => choose(active + 1)}><ChevronRight size={19} /></button></div></div></div></section>;
}

export default function Home() {
  const utils = trpc.useUtils(); const { data: stock } = trpc.orders.status.useQuery(undefined, { refetchInterval: 30_000 }); const order = trpc.orders.create.useMutation({ onSuccess: () => utils.orders.status.invalidate() });
  const [quantity, setQuantity] = useState<1 | 2>(1); const [source, setSource] = useState<Attribution>(blankAttribution); const [started, setStarted] = useState(false); const [half, setHalf] = useState(false); const [notice, setNotice] = useState(""); const remaining = stock?.remaining ?? 1000;
  useEffect(() => { setSource(attribution()); window.fbq?.("track", "ViewContent", { content_ids: ["tempo-3ml"], content_type: "product", value: 499000, currency: "VND" }); const count = () => { if (!half && (scrollY + innerHeight) / document.documentElement.scrollHeight >= .5) { window.fbq?.("trackCustom", "Scroll50"); setHalf(true); } }; addEventListener("scroll", count, { passive: true }); count(); return () => removeEventListener("scroll", count); }, [half]);
  const startForm = () => { if (!started) { window.fbq?.("trackCustom", "FormStart", { content_name: "TEMPO 3ml COD" }); setStarted(true); } };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setNotice(""); const form = event.currentTarget; const data = new FormData(form); window.fbq?.("track", "InitiateCheckout", { content_ids: ["tempo-3ml"], content_type: "product", num_items: quantity, value: quantity * 499000, currency: "VND" }); order.mutate({ fullName: String(data.get("fullName") || ""), phone: String(data.get("phone") || ""), address: String(data.get("address") || ""), note: String(data.get("note") || ""), orderConsent: data.get("orderConsent") === "on", marketingConsent: data.get("marketingConsent") === "on", quantity, ...source }, { onSuccess: result => { if (result.kind === "created") { window.fbq?.("track", "Purchase", { content_ids: ["tempo-3ml"], content_type: "product", order_id: result.order.orderNumber, num_items: result.order.quantity, value: result.order.totalValue, currency: "VND" }); window.fbq?.("trackCustom", "OrderCodSuccess", { order_id: result.order.orderNumber, value: result.order.totalValue, currency: "VND" }); setNotice(`Đơn ${result.order.orderNumber} đã được ghi nhận. V2JOY sẽ liên hệ xác nhận trước khi gửi COD.`); form.reset(); setQuantity(1); } else setNotice(result.kind === "existing" ? "Số điện thoại này đã có một đơn TEMPO đang được xử lý. V2JOY sẽ liên hệ xác nhận." : "TEMPO hiện đã hết hàng. Cảm ơn bạn đã quan tâm."); }, onError: error => setNotice(error.message || "Không thể tạo đơn lúc này. Vui lòng thử lại.") }); };
  return <main className="tempo-site">
    <header className="tempo-header"><a href="#top" className="tempo-brand" aria-label="V2JOY, TEMPO 3ml"><Image src={A.logo} alt="V2JOY" eager /><span>TEMPO</span><small>3ML / COD</small></a><nav aria-label="Điều hướng chính"><a href="#san-pham">Sản phẩm</a><a href="#nghi-thuc">Nghi thức</a><a href="#thong-tin">Thông tin</a></nav><button className="header-order" type="button" onClick={scrollToOrder}>Đặt COD <ArrowRight size={15} /></button></header>
    <section className="tempo-hero" id="top" aria-labelledby="hero-title"><Backdrop video={A.v1} poster={A.hero} label="Video 01: khoảng dừng trước buổi tối" eager /><div className="tempo-hero__wash" /><div className="tempo-hero__noise" /><div className="hero-content"><p className="overline">V2JOY / TEMPO 3ML / CẢNH 01</p><h1 id="hero-title">Chậm một nhịp.<br /><em>Gần nhau hơn.</em></h1><p className="hero-copy">Một nghi thức chăm sóc kín đáo trước những khoảnh khắc riêng tư — để sự chuẩn bị có thêm chủ động, nhẹ nhàng và đúng nhịp của hai người.</p><div className="hero-actions"><button className="button-primary" type="button" onClick={scrollToOrder}>Đặt hàng COD <ArrowRight size={17} /></button><a href="#nghi-thuc" className="button-text">Xem nghi thức <ArrowDown size={15} /></a></div></div><div className="hero-counter"><b>{remaining.toLocaleString("vi-VN")}</b><span>chai 3ml<br />sẵn sàng nhận đơn</span></div><div className="hero-footer"><span>CẢNH 01 / 05</span><Signal /><span>499.000Đ · THANH TOÁN COD</span></div></section>
    <div className="proof-strip" aria-label="Cam kết trải nghiệm"><span><LockKeyhole size={16} /> Đóng gói kín đáo</span><span><PackageCheck size={16} /> Thanh toán COD</span><span><ClipboardCheck size={16} /> Thông tin rõ trên nhãn</span><span><ShieldCheck size={16} /> Gọi xác nhận đơn</span></div>
    <section className="commerce-intro" id="san-pham" aria-labelledby="why-title"><div><p className="chapter">VÌ SAO BẮT ĐẦU</p><p className="commerce-intro__eyebrow">TRƯỚC KHI NÓI VỀ SẢN PHẨM</p></div><div><h2 id="why-title">Chuẩn bị kỹ hơn.<br /><em>Để buổi tối tự nhiên hơn.</em></h2><p>TEMPO 3ml là một lựa chọn chăm sóc da nhỏ gọn, với cách dùng và thông tin nhãn rõ ràng cho khoảng chuẩn bị riêng của bạn.</p></div><div className="commerce-intro__side"><Clock3 size={20} /><p>TEMPO là mỹ phẩm chăm sóc da. Sản phẩm không thay thế sự kết nối, giao tiếp và đồng thuận giữa hai người.</p></div></section>
    <Scene step="02" title="Khép lại ngày dài." accent="Mang theo điều vừa đủ." copy="Bỏ chai vào túi. Rời khỏi lịch làm việc. Giữ một khoảng chuẩn bị riêng cho buổi tối mà bạn đã chọn." detail="MỘT CHAI NHỎ · MỘT NHỊP CHỦ ĐỘNG" video={A.v2} poster={A.carry} />
    <section className="product-proof" aria-labelledby="product-title"><div className="product-proof__image product-proof__image--square"><Image src={A.product} alt="TEMPO 3ml: hộp và chai sản phẩm" className="mobile-safe-square" /><span>3ML / NHỎ GỌN</span></div><div className="product-proof__copy"><p className="overline overline--dark">TEMPO 3ML / MANG THEO</p><h2 id="product-title">Nhỏ để mang theo.<br /><em>Dễ bắt đầu.</em></h2><p>Một chai TEMPO 3ml cho nhịp chăm sóc kín đáo. Sản phẩm lô đầu tiên có giá 499.000đ/chai, thanh toán khi nhận hàng.</p><dl><div><dt>Dung tích</dt><dd>3ml</dd></div><div><dt>Đơn tối đa</dt><dd>02 chai</dd></div><div><dt>Tình trạng</dt><dd>Còn {remaining.toLocaleString("vi-VN")} / 1.000</dd></div></dl><button type="button" className="text-button" onClick={scrollToOrder}>Đặt TEMPO 3ml <ArrowRight size={16} /></button></div></section>
    <ProductDetails />
    <Scene step="03" title="Dừng lại để đọc." accent="Biết trước khi chọn." copy="Sản phẩm chăm sóc da không cần được hứa quá. Bạn có thể xem thành phần, đối chiếu nhãn và chọn theo điều mình hiểu rõ." detail="ĐỌC INCI · ĐỐI CHIẾU NHÃN · TỰ QUYẾT ĐỊNH" video={A.v3} poster={A.label} />
    <section className="ritual-section ritual-section--asset" id="nghi-thuc" aria-labelledby="ritual-title"><div className="ritual-copy"><p className="overline">NGHI THỨC TEMPO</p><h2 id="ritual-title">Ba bước.<br /><em>Đúng nhịp.</em></h2><ol><li><b>01</b><span>Vệ sinh sạch vùng da cơ thể và lắc đều sản phẩm.</span></li><li><b>02</b><span>Để chai cách vùng da cần chăm sóc khoảng 3–5 cm; xịt 3–4 nhát.</span></li><li><b>03</b><span>Chờ 60 phút, sau đó rửa sạch.</span></li></ol><p className="ritual-disclaimer">Chỉ dùng ngoài da. Đọc kỹ cảnh báo và đối chiếu nhãn thành phẩm của lô hàng trước khi sử dụng.</p></div><Image src={A.steps} alt="Ba bước sử dụng TEMPO: làm sạch, xịt 3–4 nhát, chờ 60 phút rồi rửa sạch" className="mobile-safe-square" /></section>
    <section className="wait-section wait-section--asset"><Image src={A.wait} alt="Khoảng chờ 60 phút trong nghi thức chăm sóc TEMPO" className="mobile-safe-square" /><div><p className="overline overline--dark">KHOẢNG CHỜ CÓ Ý NGHĨA</p><h2>60 phút cho<br /><em>một nhịp chuẩn bị.</em></h2><p>Chăm sóc bản thân. Chuẩn bị không gian. Bắt đầu cuộc trò chuyện. Để khoảng chờ là một phần của sự chủ động.</p></div></section>
    <Scene step="04" title="Đến cuộc hẹn." accent="Có mặt cho nhau." copy="Một khung cảnh bình tĩnh, đặt sự có mặt lên trước mọi vội vàng. TEMPO chỉ là một bước chăm sóc trong nhịp riêng của bạn." detail="BÌNH TĨNH · TÔN TRỌNG · ĐỒNG THUẬN" video={A.v4} poster={A.hands} />
    <Diary />
    <Scene step="05" title="Giữ nhịp riêng." accent="Nhẹ nhàng kết thúc." copy="Từ một chai nhỏ đến một buổi tối bạn đã chọn — mọi thứ đều bắt đầu bằng việc hiểu rõ điều mình dùng." detail="TEMPO 3ML · KÍN ĐÁO · RÕ RÀNG" video={A.v5} poster={A.story} />
    <section className="transparency" id="thong-tin" aria-labelledby="info-title"><div className="section-masthead"><p className="overline overline--dark">THÔNG TIN SẢN PHẨM</p><h2 id="info-title">Rõ ràng từ<br /><em>thành phần đến nhãn.</em></h2><p>Thông tin dưới đây được trình bày để bạn kiểm tra trước khi đặt đơn COD. Nhãn in trên sản phẩm của từng lô luôn là nguồn ưu tiên.</p></div><div className="label-gallery"><figure><Image src={A.sides} alt="Các mặt cạnh hộp TEMPO có hướng dẫn nghi thức" className="mobile-safe-square" /><figcaption>Nghi thức sử dụng</figcaption></figure><figure><Image src={A.back} alt="Mặt sau hộp TEMPO có thông tin hướng dẫn, bảo quản và xuất xứ" className="mobile-safe-square" /><figcaption>Hướng dẫn và bảo quản</figcaption></figure><figure><Image src={A.label} alt="Chi tiết chai TEMPO gồm nắp, vòi xịt và nhãn" className="mobile-safe-square" /><figcaption>Chi tiết chai 3ml</figcaption></figure></div><div className="safety-grid"><article><TimerReset size={21} /><h3>Hướng dẫn</h3><p>Lắc đều. Xịt 3–4 nhát cách da khoảng 3–5 cm, chờ 60 phút rồi rửa sạch.</p></article><article><ShieldCheck size={21} /><h3>Cảnh báo</h3><p>Chỉ dùng ngoài da. Không dùng trên vùng da trầy xước; ngưng dùng nếu có kích ứng.</p></article><article><ClipboardCheck size={21} /><h3>Bảo quản</h3><p>Nơi khô ráo, thoáng mát, dưới 30°C; tránh nắng trực tiếp và đóng kín nắp sau khi dùng.</p></article></div><div className="product-information" id="inci-full"><div className="product-information__copy"><p className="overline overline--dark">ĐỐI CHIẾU NHÃN</p><h3>Danh mục rõ ràng.<br /><em>Không cần đoán.</em></h3><p><b>Mục đích sử dụng ghi nhận:</b> giúp chăm sóc dưỡng ẩm da.</p><p>Vì có chiết xuất thiên nhiên, sản phẩm có thể lắng nhẹ; lắc đều trước khi sử dụng.</p></div><div className="product-information__details"><details><summary>Danh mục thành phần (INCI) <ChevronDown size={17} /></summary><p>{INCI}</p></details><details><summary>Cảnh báo và hạn sử dụng <ChevronDown size={17} /></summary><p>Chỉ dùng ngoài da, không được uống. Không dùng với người mẫn cảm với bất kỳ thành phần nào. Không xịt lên vùng da có vết thương hở hoặc đang trầy xước. Ngưng sử dụng và tham khảo ý kiến chuyên gia khi có dấu hiệu kích ứng, mẩn đỏ. Hạn sử dụng: 24 tháng kể từ ngày sản xuất.</p></details></div></div><div className="provenance-card"><Leaf size={22} /><div><span>SẢN XUẤT VÀ CHỊU TRÁCH NHIỆM</span><h3>Chi nhánh Hà Nam – Công ty TNHH Sản xuất DP Công nghệ cao Nanofrance</h3><p>Khu công nghiệp Đồng Văn IV, Phường Lê Hồ, Tỉnh Ninh Bình, Việt Nam. Xuất xứ: Việt Nam. Website trên nhãn: <a href="https://www.nanofrance.com.vn" target="_blank" rel="noreferrer">www.nanofrance.com.vn</a>. Số công bố hiển thị: 354/20/CBMP-NB.</p><small>Vui lòng đối chiếu số lô, NSX/HSD, số công bố và pháp nhân trên nhãn thành phẩm của lô hàng bạn nhận.</small></div></div></section>
    <section className="order-section" id="dat-hang" aria-labelledby="order-title"><div className="order-intro"><p className="overline overline--dark">TEMPO 3ML / COD</p><h2 id="order-title">Sẵn sàng cho<br /><em>nhịp của hai.</em></h2><p>Để lại thông tin nhận hàng. V2JOY gọi xác nhận trước khi gửi đi; bạn chỉ thanh toán khi nhận hàng.</p><div className="stock-status"><span /> Còn {remaining.toLocaleString("vi-VN")} / 1.000 chai</div></div><form className="cod-form" data-clarity-mask="true" onFocus={startForm} onSubmit={submit}><div className="product-line"><Image src={A.product} alt="Hộp TEMPO 3ml" /><div><span>TEMPO 3ML</span><strong>{vnd(499000)}</strong><small>Thanh toán COD sau khi nhận hàng</small></div></div><fieldset className="quantity-field"><legend>Chọn số lượng</legend><div role="radiogroup" aria-label="Chọn số lượng TEMPO 3ml"><button type="button" aria-pressed={quantity === 1} onClick={() => setQuantity(1)}>01 <small>chai</small></button><button type="button" aria-pressed={quantity === 2} onClick={() => setQuantity(2)}>02 <small>chai</small></button></div></fieldset><label>Họ và tên<input name="fullName" autoComplete="name" required placeholder="Tên người nhận" /></label><label>Số điện thoại<input name="phone" autoComplete="tel" inputMode="tel" required placeholder="Ví dụ: 090 123 4567" /></label><label>Địa chỉ nhận hàng<textarea name="address" autoComplete="street-address" required placeholder="Số nhà, đường, phường/xã, quận/huyện, tỉnh/thành" /></label><label>Lời nhắn <small>(không bắt buộc)</small><input name="note" placeholder="Thời điểm thuận tiện để nhận cuộc gọi..." /></label><div className="order-total"><span>Tạm tính <small>Phí giao được xác nhận trước khi gửi</small></span><strong>{vnd(quantity * 499000)}</strong></div><label className="checkline"><input name="orderConsent" type="checkbox" required /><span>Tôi đồng ý để V2JOY dùng thông tin này để xác nhận và giao đơn COD.</span></label><label className="checkline checkline-subtle"><input name="marketingConsent" type="checkbox" /><span>Tôi đồng ý nhận thông tin TEMPO từ V2JOY. <em>Không bắt buộc.</em></span></label><button className="submit-order" type="submit" disabled={order.isPending || remaining < 1}>{order.isPending ? "Đang ghi nhận..." : remaining < 1 ? "TEMPO đã hết hàng" : <>Ghi nhận đơn COD <ShoppingBag size={17} /></>}</button><p className="privacy-note"><LockKeyhole size={13} /> Thông tin dùng riêng để xử lý đơn, không hiển thị công khai.</p>{notice && <p className="form-notice" role="status"><CheckCircle2 size={17} />{notice}</p>}</form></section>
    <section className="trust-section"><div><p className="overline">V2JOY / CAM KẾT MINH BẠCH</p><h2>Niềm tin bắt đầu<br /><em>từ sự thật.</em></h2><p>Chúng tôi không hiển thị rating hay review chưa được xác minh. Đánh giá từ khách đã mua và hoàn tất giao hàng sẽ được công bố tại đây khi có dữ liệu hợp lệ.</p></div><aside><CheckCircle2 size={24} /><h3>Đánh giá đã xác minh</h3><p>Đang thu thập sau các đơn giao thành công.</p><span>Không dùng review tạo sẵn hoặc rating giả.</span></aside></section><section className="final-cta"><Image src={A.product} alt="TEMPO 3ml và hộp sản phẩm" className="mobile-safe-square" /><div><p className="overline">TEMPO 3ML / 499.000Đ</p><h2>Đặt một chai.<br /><em>Giữ một nhịp.</em></h2><p>Đặt hàng COD. V2JOY gọi xác nhận trước khi giao.</p><button className="button-primary" type="button" onClick={scrollToOrder}>Đặt hàng COD <ArrowRight size={17} /></button></div></section><footer><span>© V2JOY VIỆT NAM</span><span>TEMPO 3ML · CHỈ DÙNG NGOÀI DA</span><button type="button" onClick={scrollToOrder}>Đặt hàng</button></footer><div className="mobile-sticky" aria-label="Đặt hàng nhanh"><div><span>TEMPO 3ML</span><b>499.000đ</b></div><button type="button" onClick={scrollToOrder}>Đặt COD <ShoppingBag size={17} /></button></div>
  </main>;
}
